server:
  port: 12000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置文件的命名方式：{application}-{profile}.yml 或 {application}-{profile}.properties
          uri: https://gitee.com/youname/config.git

  # rabbitmq的配置信息；如下配置的rabbit都是默认值，其实可以完全不配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh