jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test
  username: root
  password: root

#激活配置文件;需要指定其它的配置文件名称
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /itcast
    username: guest
    password: guest

#tomcat端口
server:
  port: 80
#日志记录级别
logging:
  level:
    com.flepeng: debug
    org.springframework: info
mybatis:
  # 实体类别名包路径
  type-aliases-package: com.flepeng.pojo
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

