# 端口
server:
  port: 8080

spring:
  application:
    name: consumer-service  # 当前服务的名称


eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka

# 负载均衡配置
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置熔断策略：
hystrix:
  command:
    default:
      circuitBreaker:
        forceOpen: false # 强制打开熔断器 默认false关闭的。测试配置是否生效
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 10 # 熔断触发最小请求次数，默认值是20
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 熔断超时设置，默认为1秒

# Fegin 配置
ribbon:
  ReadTimeout: 5000 # 读取超时时长
  ConnectTimeout: 2000 # 建立链接的超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试

  # Feign默认也有对Hystrix的集成，默认是关闭的
  hystrix:
    enabled: true # 开启Feign的熔断功能

  # 压缩
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩


## 租约续约间隔时间，默认30秒
#eureka.instance.lease-renewal-interval-in-seconds: 2
## 每隔多久获取服务中心列表，(只读备份)
#eureka.client.registry-fetch-interval-seconds: 30
## 租约到期，服务时效时间，默认值90秒
#eureka.instance.lease-expiration-duration-in-seconds: 3
#


### 服务降级的三种情况：
## 服务彻底不可用
## 服务访问超时了
## 服务熔断器开启了 ，服务降级